version: "3.8"
services:
  web:
    image: newrushiflyer/lisp-clinic:1.0.0
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres?user=postgres&password=secret 
  db:
    image: postgres:14.8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdb:/var/lib/postgresql/data
volumes:
  pgdb:
