name: Build
on: push
jobs:
  lint-cljs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install node_modules
        run: npm ci
      - name: Lint
        run: cd cljs && npm run lint
