name: Build
on: push
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Clojure
        run: >
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1273.sh
          chmod +x linux-install-1.11.1.1273.sh
          sudo ./linux-install-1.11.1.1273.sh
      - name: Lint
        run: clj -M:lint
